### ISSUE TITLE
Cannot find module './json/session.json'

### ISSUE THREAD

**Issue by sukui** [NetEase/pomelo-robot-demo#1]
初学，还望多多指教！

module.js:340
    throw err;
          ^
Error: Cannot find module './json/session.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/sukui/source/node/pomelo-robot-demo/app/data/mysql.js:4:15)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by piaohai** [comment]
mysql.js 里有session.json的文件格式说明的。请参考自己新建一个就可以

**Comment by sukui** [comment]
so ga ! thinks
