### ISSUE TITLE
启动master和client后再web端点击“go”按钮，client端报错，请问是我哪里没有配置正确

### ISSUE THREAD

**Issue by susie2011** [NetEase/pomelo-robot-demo#4]
TypeError: Cannot read property 'uid' of undefined
    at evalmachine.<anonymous>:441:18
    at Query.selectCb [as _callback](C:UsersAdministratorDesktoppomelo-robotpomelo-robot-demo-masterappdatamysql.js:21:13)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:66:24)
    at C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\Protocol.js:261:16
    at Array.forEach (native)
    at Protocol._delegateError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\Protocol.js:260:17)
    at Handshake.<anonymous> (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\Protocol.js:98:12)
    at Handshake.emit (events.js:95:17)
    at Handshake.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\sequences\Sequence.js:61:12)
    at Protocol.handleNetworkError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master\node_modules\mysql\lib\protocol\Protocol.js:238:14)TypeError: Cannot read property 'uid' of undefined
    at evalmachine.<anonymous>:441:18
    at Query.selectCb [as _callback](C:UsersAdministratorDesktoppomelo-robotpomelo-robot-demo-master11appdatamysql.js:21:13)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:66:24)
    at C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:261:16
    at Array.forEach (native)
    at Protocol._delegateError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:260:17)
    at Handshake.<anonymous> (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:98:12)
    at Handshake.emit (events.js:95:17)
    at Handshake.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:61:12)
    at Protocol.handleNetworkError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:238:14)TypeError: Cannot read property 'uid' of undefined
    at evalmachine.<anonymous>:441:18
    at Query.selectCb [as _callback](C:UsersAdministratorDesktoppomelo-robotpomelo-robot-demo-master11appdatamysql.js:21:13)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:66:24)
    at C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:261:16
    at Array.forEach (native)
    at Protocol._delegateError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:260:17)
    at Handshake.<anonymous> (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:98:12)
    at Handshake.emit (events.js:95:17)
    at Handshake.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:61:12)
    at Protocol.handleNetworkError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:238:14)TypeError: Cannot read property 'uid' of undefined
    at evalmachine.<anonymous>:441:18
    at Query.selectCb [as _callback](C:UsersAdministratorDesktoppomelo-robotpomelo-robot-demo-master11appdatamysql.js:21:13)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:66:24)
    at C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:261:16
    at Array.forEach (native)
    at Protocol._delegateError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:260:17)
    at Handshake.<anonymous> (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:98:12)
    at Handshake.emit (events.js:95:17)
    at Handshake.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:61:12)
    at Protocol.handleNetworkError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:238:14)TypeError: Cannot read property 'uid' of undefined
    at evalmachine.<anonymous>:441:18
    at Query.selectCb [as _callback](C:UsersAdministratorDesktoppomelo-robotpomelo-robot-demo-master11appdatamysql.js:21:13)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:66:24)
    at C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:261:16
    at Array.forEach (native)
    at Protocol._delegateError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:260:17)
    at Handshake.<anonymous> (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:98:12)
    at Handshake.emit (events.js:95:17)
    at Handshake.Sequence.end (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\sequences\Sequence.js:61:12)
    at Protocol.handleNetworkError (C:\Users\Administrator\Desktop\pomelo-robot\pomelo-robot-demo-master11\node_modules\mysql\lib\protocol\Protocol.js:238:14)

**Comment by NextZeus** [comment]
朋友， 你本地有产生mysql 数据没？ 
先用genHero跑一遍，跑出来数据， 再queryHero
